name: "Develop Deploy"

on:
  push:
    branches:
      - develop
    paths:
      - 'infra/**'

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    uses: ./.github/workflows/terraform.yml
    with:
      environment: dev
      aws-assume-role-arn: "arn:aws:iam::{{ secrets.AWS_ACCOUNT }}:role/${{ secrets.AWS_ROLE }}"
      aws-region: "${{ secrets.AWS_REGION }}"
