name: "Develop Deploy"

on:
  pull_request:
    branches:
      - develop
    paths:
      - 'infra/**'
  issue_comment:
    types: [created]

permissions:
  id-token: write
  contents: read
  pull-requests: write
  issues: write

jobs:

  terraform:
    uses: ./.github/workflows/terraform.yml
    with:
      environment: dev

    secrets: inherit
      # aws-assume-role-arn: "arn:aws:iam::${{ secrets.AWS_ACCOUNT }}:role/${{ secrets.AWS_ROLE }}"
      # aws-region: "${{ secrets.AWS_REGION }}"
    
