name: "Develop Deploy"

on:
  pull_request:
    branches:
      - develop
    paths:
      - 'infra/**'

permissions:
  id-token: write
  contents: read

env:
  AWS_ACCOUNT: ${{ secrets.AWS_ACCOUNT }}
  AWS_REGION: ${{ secrets.AWS_REGION }}
  AWS_ROLE: ${{ secrets.AWS_ROLE }}

jobs:
  terraform:
    uses: ./.github/workflows/terraform.yml
    with:
      environment: dev
      aws-assume-role-arn: arn:aws:iam::{{ env.AWS_ACCOUNT }}:role/${{ env.AWS_ROLE }}
      aws-region: ${{ env.AWS_REGION }}
