name: "Develop Deploy"

on:
  pull_request:
    branches:
      - develop
    paths:
      - 'infra/**'

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Print secrets
        run: echo "AWS_ACCOUNT: ${{ secrets.AWS_ACCOUNT }}"
        
  terraform:
    uses: ./.github/workflows/terraform.yml
    with:
      environment: dev
      aws-assume-role-arn: "arn:aws:iam::${{ secrets.AWS_ACCOUNT }}:role/${{ secrets.AWS_ROLE }}"
      aws-region: "${{ secrets.AWS_REGION }}"
    secrets: inherit
