name: "Develop Deploy"

on:
  pull_request:
    branches:
      - develop
    paths:
      - 'infra/**'

permissions:
  contents: read
  pull-requests: write

jobs:
  terraform:
    uses: ./.github/workflows/terraform.yml
    with:
      environment: dev
