name: "Develop Deploy"

on:
  pull_request:
    branches:
      - develop
    paths:
      - 'infra/**'
    
permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:

  provider:
    uses: ./.github/workflows/provider.yml
    secrets: inherit

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      run: |
        echo " ${{ needs.provider.outputs.workdir }} "

  # terraform:
  #   uses: ./.github/workflows/terraform.yml
  #   with:
  #     environment: dev
  #   secrets: inherit
    