name: "Stage Deploy"

on:
  pull_request:
    branches:
      - stage
    paths:
      - 'infra/**'
    
permissions:
  id-token: write
  contents: write
  pull-requests: write

jobs:

  terraform:
    uses: ./.github/workflows/terraform.yml
    with:
      environment: stg
      provider_oidc_role: github-actions-iac-role    