name: 'Terraform Apply'

on:
  pull_request:
    branches:
      - main
      - stage
      - develop
  issue_comment:
    types: [created]

permissions:
  pull-requests: write
  issues: write  
  contents: write

jobs:

  apply: 
    if: >
      github.event_name == 'issue_comment' &&
      github.event.comment.body == '/apply'

    runs-on: ubuntu-latest

    permissions:
      pull-requests: write
      issues: write  
      contents: write
      
    defaults:
      run:
        shell: bash

    steps:

      - name: Debug Github
        run: echo ${{ toJSON(github) }}