name: 'Terraform Apply'

on:
  pull_request:
    branches:
      - develop
    types: [opened, synchronize]
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]

jobs:

  apply: 
    if: >
      github.event_name == 'issue_comment' &&
      github.event.comment.body == '/apply'

    runs-on: ubuntu-latest

    permissions:
      pull-requests: write  # Required for commenting on PRs
      contents: read        # Required for checking out code
      
    defaults:
      run:
        shell: bash

    steps:

      - name: Debug Github
        run: echo ${{ toJSON(github) }}