name: 'Terraform Apply'

on:
  pull_request:
    branches:
      - develop
    paths:
      - 'infra/**'
  issue_comment: # issue_comment.created
    types: [created]

jobs:

  apply: 
    if: >
      github.event_name == 'issue_comment' &&
      contains(github.event.comment.body, '/apply')
    runs-on: ubuntu-latest
      
    defaults:
      run:
        shell: bash

    steps:

      - name: Debug Github
        run: echo ${{ toJSON(github) }}