name: 'Terraform Apply'

on:
  issue_comment: 
    types: [created]

jobs:

  apply: 
    if: >
      github.event_name == 'issue_comment' &&
      github.event.comment.body == '/apply'

    runs-on: ubuntu-latest

    permissions:
      pull-requests: write
      issues: write  
      contents: write
      
    defaults:
      run:
        shell: bash

    steps:

      - name: Debug Github
        run: echo ${{ toJSON(github) }}