name: 'Terraform Apply'

on:
  pull_request:
    branches:
      - develop
    types: [opened, synchronize, reopened, labeled, unlabeled, ready_for_review, locked, unlocked, edited, closed, reopened ]
  issue_comment:
    types: [created]

jobs:

  apply: 
    if: |
      github.event.issue.pull_request && 
      contains(github.event.comment.body, '/apply')

    runs-on: ubuntu-latest

    permissions:
      pull-requests: write
      contents: read
      issues: write    # Required for commenting
      
    defaults:
      run:
        shell: bash

    steps:

      - name: Debug Github
        run: echo ${{ toJSON(github) }}